@echo off
echo Levantando infraestructura Docker...
docker-compose up -d --build
echo Esperando a que el servidor este listo...
timeout /t 5
echo Abriendo Dashboard...
start http://localhost:5173
docker-compose logs -f