
services:
  #mosquitto:
  #  image: eclipse-mosquitto
  #  container_name: mosquitto
  #  ports:
  #    - "1883:1883"
  #  volumes:
  #    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    #depends_on:
    #  - mosquitto

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  #simulator:
    #build: ./simulator
    #container_name: simulator
    #depends_on:
     # - mosquitto